---@meta

---BT is short for BodyType
BT = {
    ['Humanoid'] = 0,
    ['Lycanthrope'] = 1,
    ['Undead'] = 2,
    ['Giant'] = 3,
    ['Construct'] = 4,
    ['Extraplanar'] = 5,
    ['Magical'] = 6,
    ['SummonedUndead'] = 7,
    ['RaidGiant'] = 8,
    ['NoTarget'] = 9,
    ['Vampire'] = 10,
    ['Atenha_Ra'] = 11,
    ['Greater_Akheva'] = 12,
    ['Khati_Sha'] = 13,
    ['Seru'] = 14,
    ['Draz_Nurakk'] = 15,
    ['Zek'] = 16,
    ['Luggald'] = 17,
    ['Animal'] = 18,
    ['Insect'] = 19,
    ['Monster'] = 20,
    ['Summoned'] = 21,
    ['Plant'] = 22,
    ['Dragon'] = 23,
    ['Summoned2'] = 24,
    ['Summoned3'] = 25,
    ['VeliousDragon'] = 26,
    ['Dragon3'] = 27,
    ['Boxes'] = 28,
    ['Muramite'] = 29,
    ['NoTarget2'] = 30,
    ['SwarmPet'] = 31,
    ['InvisMan'] = 32,
    ['Special'] = 33,
}