---@meta

---@class Language
---@field CommonTongue number -- 0
---@field Barbarian number -- 1
---@field Erudian number -- 2
---@field Elvish number -- 3
---@field DarkElvish number -- 4
---@field Dwarvish number -- 5
---@field Troll number -- 6
---@field Ogre number -- 7
---@field Gnomish number -- 8
---@field Halfling number -- 9
---@field ThievesCant number -- 10
---@field OldErudian number -- 11
---@field ElderElvish number -- 12
---@field Froglok number -- 13
---@field Goblin number -- 14
---@field Gnoll number -- 15
---@field CombineTongue number -- 16
---@field ElderTeirDal number -- 17
---@field Lizardman number -- 18
---@field Orcish number -- 19
---@field Faerie number -- 20
---@field Dragon number -- 21
---@field ElderDragon number -- 22
---@field DarkSpeech number -- 23
---@field VahShir number -- 24
---@field Alaran number -- 25
---@field Hadal number -- 26
---@field Unknown number -- 27
---@field MaxValue number
---@field Unknown27 number
Language = {}